services:
  spark-master:
    image: apache/spark:3.5.3
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./defaultLakehouse:/opt/spark/data
      - ./:/home/ien/Projects/qb

  spark-worker:
    image: apache/spark:3.5.3
    container_name: spark-worker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker -m 1G -c 1 spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./defaultLakehouse:/opt/spark/data
      - ./:/home/ien/Projects/qb

  backend:
    build: ./backend
    container_name: qb-backend
    depends_on:
      - spark-master
    environment:
      - APP_SPARK_MASTER=spark://spark-master:7077
      - APP_SPARK_WAREHOUSE_DIR=/opt/spark/data
      - APP_CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    volumes:
      - ./defaultLakehouse:/opt/spark/data
      - ./:/home/ien/Projects/qb
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: qb-frontend
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    ports:
      - "3000:3000"
